# 🔥 IIT Roorkee Campus Immersion is About to Change Everything

Forget the usual.

This isn’t another online session or a webinar you half-watch from your couch.

This is **real**.

Classrooms that have shaped some of India’s sharpest minds.
A campus buzzing with legacy, innovation, and energy.
And for a few unforgettable days, **it’s yours**.

Learners are already locking in their travel plans.
Group chats are blowing up.
The cohort is coming alive.

And trust us — you don’t want to be the one who missed it.

## Here’s what’s waiting on the other side:

🤖 **Build real AI Agents**
Hands-on, practical, and far beyond just theory.

⚡ **Compete in a high-energy Hackathon**
Push your limits, test your ideas, and build something that matters.

🤝 **Meet your people**
Founders, builders, thinkers, and ambitious peers — all in one place.

🏛️ **Live and breathe IIT Roorkee**
The campus, the culture, and the conversations that don’t end at midnight.

🚀 **Leave transformed**
With new skills, unforgettable stories, and a network that lasts.

The energy is already electric.
The cohort is assembling.

The only question is:

## Are you in?

🎓 **Secure your spot before someone else takes it.**
This one’s going to be legendary.

In [1]:
# !pip install openai python-dotenv pandas
import pandas as pd
import os, json, time
from dotenv import load_dotenv
from openai import OpenAI
import textwrap

import truststore
truststore.inject_into_ssl()



def pretty_print(*args):
    text = " ".join(str(arg) for arg in args)
    try:
        print(textwrap.fill(text, width=80))
    except Exception as e:
        print(text)  # fallback to normal print if text is not a string

        

load_dotenv('/Users/shivam13juna/Documents/scaler/iitr_classes/llm_ref/openai_key.env')  # reads .env file in the current directory

api_key = os.getenv("OPENAI_API_KEY")

if not api_key:
    raise ValueError(
        "OPENAI_API_KEY not found! "
        "Make sure you have a .env file with: OPENAI_API_KEY=sk-..."
    )

pretty_print("API key loaded successfully.")

MODEL = 'gpt-5-nano'




client = OpenAI(api_key=api_key)
pretty_print("OpenAI client ready.")

API key loaded successfully.
OpenAI client ready.

In [2]:
products = [
    {"id": "P001", "name": "Wireless Bluetooth Headphones", "description": "Over-ear wireless headphones with active noise cancellation, 30-hour battery life, and foldable design. Features Bluetooth 5.3 and multipoint connectivity."},
    {"id": "P002", "name": "Ergonomic Office Chair", "description": "Adjustable lumbar support office chair with breathable mesh back, 4D armrests, seat depth adjustment, and 135-degree recline. Supports up to 300 lbs."},
    {"id": "P003", "name": "Stainless Steel Water Bottle", "description": "Double-wall vacuum insulated 1-liter water bottle. Keeps drinks cold 24 hours or hot 12 hours. BPA-free, leak-proof lid with carrying loop."},
    {"id": "P004", "name": "Mechanical Keyboard", "description": "Compact 75% layout mechanical keyboard with hot-swappable switches, RGB backlighting, gasket mount structure, and PBT double-shot keycaps. USB-C and wireless."},
    {"id": "P005", "name": "Portable Power Station", "description": "500Wh portable power station with LiFePO4 battery, 800W pure sine wave AC output, 100W USB-C PD charging, and solar panel input. Weighs 14 lbs."},
    {"id": "P006", "name": "Smart Doorbell Camera", "description": "2K HDR video doorbell with 180-degree field of view, two-way audio, night vision, and local storage via microSD. Works with Alexa and Google Home."},
    {"id": "P007", "name": "Air Purifier", "description": "HEPA 13 air purifier covering 1,200 sq ft. Auto mode with air quality sensor, whisper-quiet 24dB sleep mode, and filter replacement indicator."},
    {"id": "P008", "name": "Camping Hammock", "description": "Ultralight double camping hammock made from 70D ripstop nylon. Holds 500 lbs. Includes tree straps, carabiners, and stuff sack. Packs down to 1 lb."},
    {"id": "P009", "name": "Electric Standing Desk", "description": "Dual-motor electric standing desk with 60x30 inch bamboo top. Height range 25.6-51.2 inches, 4 memory presets, cable management tray, and anti-collision sensor."},
    {"id": "P010", "name": "Robot Vacuum Cleaner", "description": "LiDAR navigation robot vacuum with 5000Pa suction, auto-empty dock, mop attachment, no-go zones via app, and 180-minute runtime on hardwood and carpet."}
]

df = pd.DataFrame(products)
df

,id,name,description
0,P001,Wireless Bluetooth Headphones,Over-ear wireless headphones with active noise...
1,P002,Ergonomic Office Chair,Adjustable lumbar support office chair with br...
2,P003,Stainless Steel Water Bottle,Double-wall vacuum insulated 1-liter water bot...
3,P004,Mechanical Keyboard,Compact 75% layout mechanical keyboard with ho...
4,P005,Portable Power Station,500Wh portable power station with LiFePO4 batt...
5,P006,Smart Doorbell Camera,2K HDR video doorbell with 180-degree field of...
6,P007,Air Purifier,"HEPA 13 air purifier covering 1,200 sq ft. Aut..."
7,P008,Camping Hammock,Ultralight double camping hammock made from 70...
8,P009,Electric Standing Desk,Dual-motor electric standing desk with 60x30 i...
9,P010,Robot Vacuum Cleaner,LiDAR navigation robot vacuum with 5000Pa suct...

In [3]:
# A short, simple system prompt — well under 1024 tokens
short_prompt = "You are an assistant that summarizes products for SEO and extracts key features. Return JSON with keys: summary (2 sentences) and features (list of 3-5 strings)."

In [4]:
naive_results = []

for product in products[:5]:  # start with 5 products
    start = time.time()
    
    response = client.responses.create(
        model=MODEL,
        instructions=short_prompt,
        input=f"Product: {product['name']}\nDescription: {product['description']}"
    )
    
    elapsed = time.time() - start
    
    usage = response.usage
    cached = usage.input_tokens_details.cached_tokens if usage.input_tokens_details else 0
    
    naive_results.append({
        "product": product["name"],
        "input_tokens": usage.input_tokens,
        "output_tokens": usage.output_tokens,
        "cached_tokens": cached,
        "latency_s": round(elapsed, 2),
        "output_preview": response.output_text[:120] + "..."
    })
    
    print(f"✅ {product['name']}: {elapsed:.2f}s | input={usage.input_tokens} | cached={cached} | output={usage.output_tokens}")

print(f"\n⏱️  Total time: {sum(r['latency_s'] for r in naive_results):.2f}s")

✅ Wireless Bluetooth Headphones: 11.53s | input=85 | cached=0 | output=1159
✅ Ergonomic Office Chair: 8.31s | input=88 | cached=0 | output=974
✅ Stainless Steel Water Bottle: 5.58s | input=86 | cached=0 | output=576
✅ Mechanical Keyboard: 14.88s | input=86 | cached=0 | output=2199
✅ Portable Power Station: 7.89s | input=95 | cached=0 | output=1018

⏱️  Total time: 48.19s

In [ ]:
from concurrent.futures import ThreadPoolExecutor, as_completed

def process_product(product):
    start = time.time()

    response = client.responses.create(
        model=MODEL,
        instructions=short_prompt,
        input=f"Product: {product['name']}\nDescription: {product['description']}"
    )

    elapsed = time.time() - start
    usage = response.usage
    cached = usage.input_tokens_details.cached_tokens if usage.input_tokens_details else 0

    return {
        "product": product["name"],
        "input_tokens": usage.input_tokens,
        "output_tokens": usage.output_tokens,
        "cached_tokens": cached,
        "latency_s": round(elapsed, 2),
        "output_preview": response.output_text[:120] + "..."
    }

naive_results = []

with ThreadPoolExecutor(max_workers=5) as executor:
    futures = [executor.submit(process_product, product) for product in products[:5]]
    
    for future in as_completed(futures):
        result = future.result()
        naive_results.append(result)
        print(
            f"✅ {result['product']}: {result['latency_s']:.2f}s | "
            f"input={result['input_tokens']} | cached={result['cached_tokens']} | "
            f"output={result['output_tokens']}"
        )

✅ Wireless Bluetooth Headphones: 6.95s | input=85 | cached=0 | output=454
✅ Stainless Steel Water Bottle: 7.00s | input=86 | cached=0 | output=617
✅ Portable Power Station: 9.36s | input=95 | cached=0 | output=1210
✅ Ergonomic Office Chair: 13.05s | input=88 | cached=0 | output=1608
✅ Mechanical Keyboard: 18.76s | input=86 | cached=0 | output=2728

⏱️  Total time: 55.12s

In [5]:
long_system_prompt = """
You are an expert e-commerce product content specialist working for a major online marketplace.
Your job is to create SEO-optimized product summaries and extract structured feature data.

=== OUTPUT FORMAT ===
You MUST respond with valid JSON only. No markdown, no explanation, just the JSON object.
{
  "seo_summary": "A compelling 2-3 sentence summary optimized for search engines. Include the product name, primary benefit, and a call-to-action phrase. Use active voice throughout.",
  "features": ["Feature 1 as a concise bullet point", "Feature 2", ...],
  "category": "The most specific product category",
  "target_audience": "Who this product is best suited for",
  "keywords": ["seo", "keyword", "list"]
}

=== WRITING STYLE GUIDE ===
1. Always write in active voice. BAD: "The battery is designed to last 30 hours." GOOD: "Enjoy 30 hours of uninterrupted battery life."
2. Lead with the primary benefit, not the feature. BAD: "Has Bluetooth 5.3" GOOD: "Connect seamlessly to all your devices with Bluetooth 5.3"
3. Use power words: discover, transform, elevate, essential, premium, revolutionary, seamless
4. Avoid superlatives without evidence. Don't say "best" or "greatest" unless the product description provides comparative data.
5. Keep sentences between 15-25 words for readability.
6. Include at least one emotional trigger word per summary (comfort, confidence, peace of mind, freedom, etc.)
7. End the SEO summary with an implicit call-to-action ("Upgrade your...", "Transform your...", "Experience...")

=== FEATURE EXTRACTION RULES ===
1. Extract 3-5 features maximum. Prioritize by consumer impact.
2. Each feature should be a standalone phrase (not a full sentence). 5-12 words each.
3. Always include the primary spec (battery life, weight, capacity, etc.) with units.
4. Group related specs into a single feature when possible.
5. Order features from most important to least important for the target consumer.

=== CATEGORY TAXONOMY ===
Use the most specific category from this hierarchy:
- Electronics > Audio > Headphones > Over-Ear / In-Ear / On-Ear
- Electronics > Computers > Peripherals > Keyboards / Mice / Monitors
- Electronics > Smart Home > Security / Lighting / Climate / Cleaning
- Furniture > Office > Chairs / Desks / Storage
- Outdoor & Sports > Camping > Shelter / Sleep / Cook / Accessories
- Kitchen & Home > Drinkware / Cookware / Appliances
- Power & Energy > Portable Power / Solar / Batteries

=== KEYWORD GUIDELINES ===
1. Generate 5-8 SEO keywords per product.
2. Include both short-tail (1-2 words) and long-tail (3-5 words) keywords.
3. Always include the product type, primary feature, and target use case.
4. Avoid brand names unless provided in the product description.
5. Include common misspellings or alternative terms consumers might search for.

=== FEW-SHOT EXAMPLES ===

EXAMPLE INPUT:
Product: Running Shoes
Description: Lightweight mesh running shoes with responsive foam cushioning, reinforced heel counter, and reflective details. Available in sizes 6-14. Weighs 8.5 oz.

EXAMPLE OUTPUT:
{
  "seo_summary": "Hit the pavement with confidence in these ultralight running shoes featuring responsive foam cushioning that absorbs impact mile after mile. The breathable mesh upper and reinforced heel deliver the perfect balance of comfort and stability. Elevate your running experience today.",
  "features": ["Responsive foam cushioning for impact absorption", "Breathable lightweight mesh upper at 8.5 oz", "Reinforced heel counter for stability", "Reflective details for low-light visibility", "Available in sizes 6 through 14"],
  "category": "Outdoor & Sports > Running > Footwear",
  "target_audience": "Recreational and intermediate runners seeking lightweight, cushioned footwear",
  "keywords": ["running shoes", "lightweight running shoes", "cushioned running shoes", "mesh running shoes", "reflective running shoes", "responsive foam shoes", "8.5 oz running shoes"]
}

EXAMPLE INPUT:
Product: Yoga Mat
Description: 6mm thick non-slip yoga mat made from natural tree rubber with alignment markings. Dimensions 72x26 inches. Includes carrying strap. Free from PVC, latex, and silicone.

EXAMPLE OUTPUT:
{
  "seo_summary": "Transform your practice on this premium natural rubber yoga mat with built-in alignment markings that guide your poses with precision. The 6mm thick non-slip surface provides the perfect cushion-to-grip ratio for any flow style. Discover your best practice with this eco-friendly essential.",
  "features": ["6mm natural tree rubber with non-slip grip", "Built-in alignment markings for guided practice", "72x26 inch full-size dimensions", "Eco-friendly: PVC, latex, and silicone free", "Includes carrying strap for portability"],
  "category": "Outdoor & Sports > Yoga > Mats",
  "target_audience": "Yoga practitioners of all levels seeking an eco-conscious, non-slip mat",
  "keywords": ["yoga mat", "non-slip yoga mat", "natural rubber yoga mat", "alignment yoga mat", "eco-friendly yoga mat", "6mm yoga mat", "yoga mat with markings"]
}

=== IMPORTANT REMINDERS ===
- Output ONLY the JSON object. No preamble, no markdown code fences, no explanation.
- If the product description is vague, make reasonable inferences but do not fabricate specific numbers.
- Use American English spelling throughout.
- Ensure all JSON keys are exactly as shown in the format specification above.
"""

# Rough token count check (1 token ≈ 4 chars for English)
estimated_tokens = len(long_system_prompt) / 4
print(f"Estimated system prompt tokens: ~{int(estimated_tokens)}")
print(f"Meets 1024-token minimum: {'✅ Yes' if estimated_tokens >= 1024 else '❌ No — need to expand'}")

Estimated system prompt tokens: ~1344
Meets 1024-token minimum: ✅ Yes

In [6]:
cache_results = []

for i, product in enumerate(products[:5]):
    start = time.time()
    
    response = client.responses.create(
        model=MODEL,
        instructions=long_system_prompt,
        input=f"Product: {product['name']}\nDescription: {product['description']}"
    )
    
    elapsed = time.time() - start
    usage = response.usage
    cached = usage.input_tokens_details.cached_tokens if usage.input_tokens_details else 0
    
    cache_results.append({
        "request_num": i + 1,
        "product": product["name"],
        "input_tokens": usage.input_tokens,
        "cached_tokens": cached,
        "cache_hit_pct": f"{(cached / usage.input_tokens * 100):.1f}%" if usage.input_tokens > 0 else "0%",
        "output_tokens": usage.output_tokens,
        "latency_s": round(elapsed, 2)
    })
    
    print(f"Request {i+1}: {product['name'][:30]:30s} | latency={elapsed:.2f}s | cached={cached}/{usage.input_tokens} tokens")

print(f"\n⏱️  Total: {sum(r['latency_s'] for r in cache_results):.2f}s")

Request 1: Wireless Bluetooth Headphones  | latency=13.30s | cached=0/1249 tokens
Request 2: Ergonomic Office Chair         | latency=24.74s | cached=1152/1252 tokens
Request 3: Stainless Steel Water Bottle   | latency=22.73s | cached=0/1250 tokens
Request 4: Mechanical Keyboard            | latency=28.03s | cached=1152/1250 tokens
Request 5: Portable Power Station         | latency=20.49s | cached=1152/1259 tokens

⏱️  Total: 109.29s

In [9]:
# First, send one more request with the ORIGINAL prompt to warm the cache
response_warm = client.responses.create(
    model=MODEL,
    instructions=long_system_prompt,
    input=f"Product: {products[5]['name']}\nDescription: {products[5]['description']}"
)
cached_warm = response_warm.usage.input_tokens_details.cached_tokens if response_warm.usage.input_tokens_details else 0
print(f"Original prompt  → cached: {cached_warm}/{response_warm.usage.input_tokens}")

# Now modify ONE WORD in the system prompt
modified_prompt = long_system_prompt.replace("expert e-commerce", "skilled e-commerce")  # just one word changed!

response_miss = client.responses.create(
    model=MODEL,
    instructions=modified_prompt,
    input=f"Product: {products[5]['name']}\nDescription: {products[5]['description']}"
)
cached_miss = response_miss.usage.input_tokens_details.cached_tokens if response_miss.usage.input_tokens_details else 0
print(f"Modified prompt   → cached: {cached_miss}/{response_miss.usage.input_tokens}")
print(f"\n💡 Changing one word in the prefix caused a cache {'MISS ❌' if cached_miss < cached_warm else 'HIT ✅'}")

Original prompt  → cached: 0/1254
Modified prompt   → cached: 0/1254

💡 Changing one word in the prefix caused a cache HIT ✅

In [8]:
INPUT_COST_PER_M = 0.05
CACHED_COST_PER_M = 0.005
OUTPUT_COST_PER_M = 0.40


def calculate_cost_from_averages(
    num_requests,
    avg_input_tokens,
    avg_cached_tokens,
    avg_output_tokens,
):
    if avg_cached_tokens > avg_input_tokens:
        raise ValueError("avg_cached_tokens cannot exceed avg_input_tokens")

    total_input = num_requests * avg_input_tokens
    total_cached = num_requests * avg_cached_tokens
    total_uncached = total_input - total_cached
    total_output = num_requests * avg_output_tokens

    input_cost = (
        (total_uncached / 1_000_000) * INPUT_COST_PER_M
        + (total_cached / 1_000_000) * CACHED_COST_PER_M
    )
    output_cost = (total_output / 1_000_000) * OUTPUT_COST_PER_M
    total_cost = input_cost + output_cost

    return {
        "num_requests": num_requests,
        "total_input_tokens": total_input,
        "cached_tokens": total_cached,
        "uncached_tokens": total_uncached,
        "output_tokens": total_output,
        "input_cost": input_cost,
        "output_cost": output_cost,
        "total_cost": total_cost,
    }


def compare_scenarios(num_requests, naive, cached):
    naive_cost = calculate_cost_from_averages(num_requests, **naive)
    cached_cost = calculate_cost_from_averages(num_requests, **cached)

    savings = naive_cost["total_cost"] - cached_cost["total_cost"]
    savings_pct = (savings / naive_cost["total_cost"]) * 100 if naive_cost["total_cost"] else 0

    return naive_cost, cached_cost, savings, savings_pct


NUM_REQUESTS = 1_000_000

naive_profile = {
    "avg_input_tokens": 4000,
    "avg_cached_tokens": 0,
    "avg_output_tokens": 100,
}

cached_profile = {
    "avg_input_tokens": 4000,
    "avg_cached_tokens": 3500,
    "avg_output_tokens": 100,
}

naive_cost, cached_cost, savings, savings_pct = compare_scenarios(
    NUM_REQUESTS,
    naive_profile,
    cached_profile,
)

print("Naive total cost:  $%.2f" % naive_cost["total_cost"])
print("Cached total cost: $%.2f" % cached_cost["total_cost"])
print("Savings:           $%.2f (%.2f%%)" % (savings, savings_pct))

Naive total cost:  $240.00
Cached total cost: $82.50
Savings:           $157.50 (65.62%)

# Batching

JSON and JSONL

**JSON** is one structured value.
**JSONL** is many JSON values, one per line.


1. Example 1


Example JSON:

```json
{
  "users": [
    { "id": 1, "name": "A" },
    { "id": 2, "name": "B" }
  ]
}
```

Example JSONL:

```json
{"id": 1, "name": "A"}
{"id": 2, "name": "B"}
```


2. Exmple 2

One whole document:

```json
{
  "orders": [
    {
      "order_id": "A1001",
      "customer": "Shivam",
      "amount": 499,
      "status": "paid"
    },
    {
      "order_id": "A1002",
      "customer": "Riya",
      "amount": 899,
      "status": "pending"
    },
    {
      "order_id": "A1003",
      "customer": "Arjun",
      "amount": 1299,
      "status": "shipped"
    }
  ]
}
```

---


One record per line:

```json
{"order_id":"A1001","customer":"Shivam","amount":499,"status":"paid"}
{"order_id":"A1002","customer":"Riya","amount":899,"status":"pending"}
{"order_id":"A1003","customer":"Arjun","amount":1299,"status":"shipped"}
```

3. Example 3

```json
[
  {"event":"login","user":"u1"},
  {"event":"search","user":"u2"},
  {"event":"logout","user":"u1"}
]
```

Adding one more record means editing the array structure carefully.

With JSONL, you just append another line:

```json
{"event":"login","user":"u1"}
{"event":"search","user":"u2"}
{"event":"logout","user":"u1"}
{"event":"purchase","user":"u3"}
```

In [11]:
batch_requests = []

for product in products:
    request = {
        "custom_id": f"product-{product['id']}",
        "method": "POST",
        "url": "/v1/responses",
        "body": {
            "model": MODEL,
            "instructions": long_system_prompt,
            "input": f"Product: {product['name']}\nDescription: {product['description']}"
        }
    }
    batch_requests.append(request)

# Write to JSONL file
batch_file_path = "batch_input.jsonl"
with open(batch_file_path, "w") as f:
    for req in batch_requests:
        f.write(json.dumps(req) + "\n")

print(f"Created {batch_file_path} with {len(batch_requests)} requests")
print(f"File size: {os.path.getsize(batch_file_path):,} bytes")

Created batch_input.jsonl with 10 requests
File size: 59,140 bytes

In [12]:
# Let's peek at what one line looks like
with open(batch_file_path) as f:
    first_line = json.loads(f.readline())

# Show structure (truncate the long prompt for readability)
preview = first_line.copy()
preview["body"] = {**preview["body"], "instructions": preview["body"]["instructions"][:100] + "..."}
print(json.dumps(preview, indent=2))

{
  "custom_id": "product-P001",
  "method": "POST",
  "url": "/v1/responses",
  "body": {
    "model": "gpt-5-nano",
    "instructions": "\nYou are an expert e-commerce product content specialist working for a major online marketplace.\nYou...",
    "input": "Product: Wireless Bluetooth Headphones\nDescription: Over-ear wireless headphones with active noise cancellation, 30-hour battery life, and foldable design. Features Bluetooth 5.3 and multipoint connectivity."
  }
}

In [13]:
# Upload the JSONL file
batch_file = client.files.create(
    file=open(batch_file_path, "rb"),
    purpose="batch"
)
print(f"Uploaded file: {batch_file.id}")
print(f"Status: {batch_file.status}")

Uploaded file: file-FZLvbLYUx3PxUjPAzjrxXe
Status: processed

In [14]:
# Create the batch job
batch_job = client.batches.create(
    input_file_id=batch_file.id,
    endpoint="/v1/responses",
    completion_window="24h",
    metadata={
        "description": "Product enrichment demo — 10 products"
    }
)

print(f"Batch ID: {batch_job.id}")
print(f"Status: {batch_job.status}")
print(f"Created at: {batch_job.created_at}")

Batch ID: batch_6a2837e739308190b84e1aea566a42d0
Status: validating
Created at: 1781020647

In [15]:
poll_start = time.time()

while True:
    job = client.batches.retrieve(batch_job.id)
    elapsed = time.time() - poll_start
    
    completed = job.request_counts.completed if job.request_counts else 0
    total = job.request_counts.total if job.request_counts else 0
    
    print(f"[{elapsed:6.1f}s] Status: {job.status:15s} | Progress: {completed}/{total}")
    
    if job.status in ["completed", "failed", "expired", "cancelled"]:
        break
    
    time.sleep(10)

print(f"\n✅ Batch finished in {elapsed:.1f}s with status: {job.status}")
if job.request_counts:
    print(f"   Completed: {job.request_counts.completed} | Failed: {job.request_counts.failed}")

[   1.7s] Status: validating      | Progress: 0/0
[  13.5s] Status: validating      | Progress: 0/0
[  25.3s] Status: validating      | Progress: 0/0
[  36.9s] Status: validating      | Progress: 0/0
[  48.7s] Status: in_progress     | Progress: 0/10
[  60.7s] Status: in_progress     | Progress: 2/10
[  72.5s] Status: in_progress     | Progress: 2/10
[  84.0s] Status: in_progress     | Progress: 2/10
[  95.6s] Status: in_progress     | Progress: 2/10
[ 107.4s] Status: in_progress     | Progress: 2/10
[ 119.1s] Status: in_progress     | Progress: 2/10
[ 130.7s] Status: in_progress     | Progress: 2/10
[ 142.8s] Status: finalizing      | Progress: 10/10
[ 154.3s] Status: completed       | Progress: 10/10

✅ Batch finished in 154.3s with status: completed
   Completed: 10 | Failed: 0

In [16]:
if job.status == "completed" and job.output_file_id:
    # Download the output file
    output_content = client.files.content(job.output_file_id)
    output_text = output_content.text
    
    # Save locally
    with open("batch_output.jsonl", "w") as f:
        f.write(output_text)
    
    # Parse each line
    batch_results = []
    for line in output_text.strip().split("\n"):
        result = json.loads(line)
        batch_results.append(result)
    
    print(f"Downloaded {len(batch_results)} results")
else:
    print(f"Batch did not complete successfully. Status: {job.status}")
    if job.error_file_id:
        error_content = client.files.content(job.error_file_id)
        print("Errors:", error_content.text[:500])

Downloaded 10 results

In [17]:
# Examine one result in detail
if batch_results:
    sample = batch_results[0]
    print(f"Custom ID: {sample['custom_id']}")
    print(f"Status code: {sample['response']['status_code']}")
    
    # The response body contains the same structure as a Responses API call
    body = sample['response']['body']
    
    # Extract the output text from the response
    output_items = body.get('output', [])
    for item in output_items:
        if item.get('type') == 'message':
            for content in item.get('content', []):
                if content.get('type') == 'output_text':
                    print(f"\nOutput text (first 300 chars):\n{content['text'][:300]}...")
    
    # Check usage
    usage = body.get('usage', {})
    print(f"\nUsage: input={usage.get('input_tokens', 'N/A')}, output={usage.get('output_tokens', 'N/A')}")
    print(f"Cached: {usage.get('input_tokens_details', {}).get('cached_tokens', 'N/A')}")

Custom ID: product-P001
Status code: 200

Output text (first 300 chars):
{
  "seo_summary": "Experience immersive, interruption-free listening with over-ear wireless headphones featuring active noise cancellation. Enjoy up to 30 hours of battery life, Bluetooth 5.3 with multipoint connectivity, and a foldable design for comfort and travel. Elevate your audio—upgrade your...

Usage: input=1249, output=2199
Cached: 1152

In [18]:
# Parse all batch results into a clean DataFrame
parsed_results = []

for result in batch_results:
    custom_id = result["custom_id"]
    status_code = result["response"]["status_code"]
    body = result["response"]["body"]
    
    # Extract output text
    output_text = ""
    for item in body.get("output", []):
        if item.get("type") == "message":
            for content in item.get("content", []):
                if content.get("type") == "output_text":
                    output_text = content["text"]
    
    usage = body.get("usage", {})
    
    parsed_results.append({
        "custom_id": custom_id,
        "status": status_code,
        "input_tokens": usage.get("input_tokens", 0),
        "cached_tokens": usage.get("input_tokens_details", {}).get("cached_tokens", 0),
        "output_tokens": usage.get("output_tokens", 0),
        "output_preview": output_text[:100]
    })

batch_df = pd.DataFrame(parsed_results)
batch_df

,custom_id,status,input_tokens,cached_tokens,output_tokens,output_preview
0,product-P001,200,1249,1152,2199,"{\n ""seo_summary"": ""Experience immersive, int..."
1,product-P002,200,1252,1152,2594,"{\n ""seo_summary"": ""Experience enduring comfo..."
2,product-P003,200,1250,1152,4082,"{\n ""seo_summary"": ""Keep drinks cold for up t..."
3,product-P004,200,1250,0,3447,"{\n ""seo_summary"": ""Transform your workspace ..."
4,product-P005,200,1259,1152,4197,"{\n ""seo_summary"": ""Power your adventures wit..."
5,product-P006,200,1254,1152,3888,"{\n ""seo_summary"": ""Experience peace of mind ..."
6,product-P007,200,1253,0,2100,"{\n ""seo_summary"": ""Purify large-scale spaces..."
7,product-P008,200,1256,1152,2408,"{\n ""seo_summary"": ""Experience camp-side comf..."
8,product-P009,200,1259,0,3093,"{\n ""seo_summary"": ""Elevate your workspace wi..."
9,product-P010,200,2139,0,1912,"{\n ""seo_summary"": ""Experience effortless, th..."

```
         Need instant response?
              /           \
           YES             NO
            |               |
     Use Responses API   Use Batch API
     (synchronous)       (50% cheaper)
            |               |
   Long static prefix?    Long static prefix?
        /       \            /       \
      YES       NO         YES       NO
       |         |          |         |
   Caching    Standard   Caching    Standard
   saves $    pricing    + Batch    Batch
   + speed              = MAX $$$   saves 50%
```

# Strucured Ouputs

In [20]:
# One messy, realistic customer email we'll reuse across the whole notebook.
# Note the signature at the end — we'll need the name + email later.
customer_email = (
    "hey, my order 10432 turned up completely smashed — the ceramic mug is in pieces. "
    "I paid 49.99 for it and honestly I'm pretty annoyed, this is the second time. "
    "I just want my money back asap, can you sort this out today?\n\n"
    "Thanks, Sam Rivera (sam.rivera@example.com)"
)
print(customer_email)

hey, my order 10432 turned up completely smashed — the ceramic mug is in pieces. I paid 49.99 for it and honestly I'm pretty annoyed, this is the second time. I just want my money back asap, can you sort this out today?

Thanks, Sam Rivera (sam.rivera@example.com)

In [22]:
response = client.responses.create(
    model=MODEL,
    input=f"Extract the category, urgency and refund amount from this customer message:\n\n{customer_email}",
    reasoning={"effort": "minimal"},
)
print(response.output_text)

- Category: Refund/Return for damaged item
- Urgency: High (customer requests immediate resolution “today” and “asap”)
- Refund amount: 49.99

In [24]:
for iteration in range(10):
    response = client.responses.create(
        model=MODEL,
        input=f"Extract the category, urgency and refund amount from this customer message:\n\n{customer_email}",
        reasoning={"effort": "minimal"},
    )
    print(f"Iteration {iteration+1}: \n {response.output_text}")

Iteration 1:
 - Category: Refund/Return (Damaged Item)
- Urgency: High (wants refund “today” for a damaged item)
- Refund amount: 49.99
Iteration 2:
 - Category: Damaged item / broken product
- Urgency: High (wants refund today and mentions “asap”)
- Refund amount: 49.99
Iteration 3:
 - Category: Refund for damaged item (payment to be refunded)
- Urgency: ASAP / today
- Refund amount: 49.99

Context: The customer reports a damaged ceramic mug from order 10432 and requests a refund of 49.99 as soon as possible.
Iteration 4:
 - Category: Refund request for damaged item (broken mug)
- Urgency: High (customer requests resolution today)
- Refund amount: 49.99
Iteration 5:
 - Category: Refund / Return (Damaged item)
- Urgency: High (requesting money back "asap" and "sort this out today")
- Refund amount: 49.99
Iteration 6:
 - Category: Damaged item / defective product
- Urgency: High (customer requests refund "asap" and wants it sorted today)
- Refund amount: 49.99 USD
Iteration 7:
 - Category: Refund / Order damage (damaged item)
- Urgency: High (customer wants resolution today and a refund ASAP)
- Refund amount: 49.99
Iteration 8:
 - Category: Product damage / broken item
- Urgency: High (customer requests refund “asap” and “sort this out today”)
- Refund amount: 49.99
Iteration 9:
 - Category: Damaged item / broken product
- Urgency: High (wants refund today and expresses annoyance)
- Refund amount: 49.99
Iteration 10:
 - Category: Product damage / broken item
- Urgency: High (customer asks to sort out today and wants refund ASAP)
- Refund amount: 49.99

In [25]:
from pydantic import BaseModel

# The contract: a valid support ticket is EXACTLY these three typed fields.
# (These are the very keys we kept asking the model for in our prompts.)
class SupportTicket(BaseModel):
    category: str
    urgency: str
    refund_amount: float

# Picture the model returning clean JSON and us doing json.loads(...) -> this dict.
# Instead of TRUSTING it (like naive_pipeline did), we VALIDATE it against the contract:
model_output = {"category": "shipping", "urgency": "high", "refund_amount": 49.99}

ticket = SupportTicket.model_validate(model_output)   # <- the gate the model's output must pass
print("✅ validated:", ticket)

# refund_amount is now a guaranteed float, so the math that crashed in Section 1 just works:
print("   refund + 5% fee:", round(ticket.refund_amount * 1.05, 2))

✅ validated: category='shipping' urgency='high' refund_amount=49.99
   refund + 5% fee: 52.49

In [26]:
from pydantic import ValidationError

# Section 2 reality #1: the model returned the amount as a STRING. Pydantic coerces it to float:
print(SupportTicket.model_validate(
    {"category": "billing", "urgency": "low", "refund_amount": "49.99"}))

# Section 2 reality #2: the model returned unparseable garbage. Pydantic rejects it — loudly,
# before a single rupee can move:
try:
    SupportTicket.model_validate(
        {"category": "billing", "urgency": "low", "refund_amount": "around fifty bucks"})
except ValidationError as e:
    print("\n🚫 Pydantic blocked the model's junk:\n", e)

category='billing' urgency='low' refund_amount=49.99

🚫 Pydantic blocked the model's junk:
 1 validation error for SupportTicket
refund_amount
  Input should be a valid number, unable to parse string as a number [type=float_parsing, input_value='around fifty bucks', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/float_parsing

In [27]:
from typing import Literal
from pydantic import Field

class SupportTicket(BaseModel):
    # Only these exact strings exist -> the model can't invent a category
    category: Literal["billing", "shipping", "technical", "account", "other"]
    urgency:  Literal["low", "medium", "high"]
    # Money is bounded -> the 100x slip can't get through
    refund_amount: float = Field(ge=0, le=500)

# The invented category the model produced in Section 2:
try:
    SupportTicket.model_validate(
        {"category": "damaged item", "urgency": "high", "refund_amount": 49.99})
except ValidationError as e:
    print("🚫 bad category :", e.errors()[0]["msg"])

# The EXACT payload from the silent-bug cell that wired $5,249:
try:
    SupportTicket.model_validate(
        {"category": "shipping", "urgency": "high", "refund_amount": 4999})
except ValidationError as e:
    print("🚫 absurd amount:", e.errors()[0]["msg"])

# A legitimate ticket still passes untouched:
print("✅", SupportTicket.model_validate(
    {"category": "shipping", "urgency": "high", "refund_amount": 49.99}))

🚫 bad category : Input should be 'billing', 'shipping', 'technical', 'account' or 'other'
🚫 absurd amount: Input should be less than or equal to 500
✅ category='shipping' urgency='high' refund_amount=49.99

In [28]:
from pydantic import field_validator

class Customer(BaseModel):
    name: str
    email: str

class SupportTicket(BaseModel):
    category: Literal["billing", "shipping", "technical", "account", "other"]
    urgency:  Literal["low", "medium", "high"]
    refund_amount: float = Field(ge=0, le=500)
    order_id: str = Field(description="The 5-digit order number")
    customer: Customer                       # <-- nested model

    @field_validator("order_id")
    @classmethod
    def must_be_5_digits(cls, v):
        if not (v.isdigit() and len(v) == 5):
            raise ValueError(f"order_id must be exactly 5 digits, got {v!r}")
        return v

# A model payload with a malformed order id is caught:
try:
    SupportTicket.model_validate({
        "category": "shipping", "urgency": "high", "refund_amount": 49.99,
        "order_id": "ABC", "customer": {"name": "Sam", "email": "sam@x.com"},
    })
except ValidationError as e:
    print("🚫", e.errors()[0]["msg"])

# A well-formed model payload validates, and the nested dict becomes a real Customer object:
t = SupportTicket.model_validate({
    "category": "shipping", "urgency": "high", "refund_amount": 49.99,
    "order_id": "10432", "customer": {"name": "Sam", "email": "sam@x.com"},
})
print("✅", t)
print("   customer email:", t.customer.email)   # nested access, fully typed

🚫 Value error, order_id must be exactly 5 digits, got 'ABC'
✅ category='shipping' urgency='high' refund_amount=49.99 order_id='10432' customer=Customer(name='Sam', email='sam@x.com')
   customer email: sam@x.com

In [29]:
# Ask the model for JSON (same fragile prompt style as Section 2)...
raw = client.responses.create(
    model=MODEL,
    input=f"Reply with ONLY JSON for these keys: category, urgency, refund_amount, "
          f"order_id, and customer (an object with name and email). "
          f"Customer message:\n\n{customer_email}",
    reasoning={"effort": "minimal"},
).output_text
print("Raw model text:\n", raw, "\n")

# ...then guard it with our contract instead of trusting it:
try:
    ticket = SupportTicket.model_validate_json(raw)   # json.loads + validate, in one call
    print("✅ validated ticket:", ticket)
except Exception as e:
    print("💥 Couldn't validate the raw text:", type(e).__name__, "-", e)
    print("   (the model wrapped it in prose/fences, so our contract never even got to run)")

Raw model text:
 {
  "category": "damaged_item",
  "urgency": "high",
  "refund_amount": 49.99,
  "order_id": "10432",
  "customer": {
    "name": "Sam Rivera",
    "email": "sam.rivera@example.com"
  }
  }

💥 Couldn't validate the raw text: ValidationError - 1 validation error for SupportTicket
category
  Input should be 'billing', 'shipping', 'technical', 'account' or 'other' [type=literal_error, input_value='damaged_item', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/literal_error
   (the model wrapped it in prose/fences, so our contract never even got to run)

In [30]:
response = client.responses.parse(
    model=MODEL,
    input=[
        {"role": "system", "content":
            "Extract the support ticket from the customer message. "
            "Infer urgency from the tone. refund_amount is what the customer paid / wants back "
            "(0 if they aren't asking for a refund)."},
        {"role": "user", "content": customer_email},
    ],
    text_format=SupportTicket,        # <- hand the model OUR class
)

ticket = response.output_parsed        # <- already a validated SupportTicket, not text
print("Type of result:", type(ticket).__name__)
print(ticket)
print()
print("category :", ticket.category)         # a guaranteed-valid Literal
print("urgency  :", ticket.urgency)
print("refund   :", ticket.refund_amount, "->", type(ticket.refund_amount).__name__)
print("order id :", ticket.order_id)
print("customer :", ticket.customer.name, "<" + ticket.customer.email + ">")

Type of result: SupportTicket
category='shipping' urgency='high' refund_amount=49.99 order_id='10432' customer=Customer(name='Sam Rivera', email='sam.rivera@example.com')

category : shipping
urgency  : high
refund   : 49.99 -> float
order id : 10432
customer : Sam Rivera <sam.rivera@example.com>

In [32]:
def process_ticket(ticket: SupportTicket):
    # Every line below is safe because `ticket` couldn't exist if it weren't valid.
    print(f"🧭 routed to    : {ticket.category} team")
    print(f"⏱️  priority     : {ticket.urgency}")
    fee_total = round(ticket.refund_amount * 1.05, 2)   # always a real number in range
    print(f"💸 refund + fee  : ${fee_total:,.2f}")       # sane, every time
    print(f"📦 order         : {ticket.order_id} for {ticket.customer.name}")

process_ticket(ticket)

🧭 routed to    : shipping team
⏱️  priority     : high
💸 refund + fee  : $52.49
📦 order         : 10432 for Sam Rivera

In [33]:
weird_email = (
    "lol idk my thing just broke — the login page keeps crashing on the app, "
    "no big deal whenever you get to it. order 88217. - Priya (priya@example.com)"
)

r = client.responses.parse(
    model=MODEL,
    input=[
        {"role": "system", "content": "Extract the support ticket. Infer urgency from tone. "
                                      "refund_amount is 0 if no refund is requested."},
        {"role": "user", "content": weird_email},
    ],
    text_format=SupportTicket,
)
t2 = r.output_parsed
print(t2, "\n")
process_ticket(t2)   # technical / low / $0.00 — routed correctly, no refund issued

category='technical' urgency='low' refund_amount=0.0 order_id='88217' customer=Customer(name='Priya', email='priya@example.com')

🧭 routed to    : technical team
⏱️  priority     : low
💸 refund + fee  : $0.00
📦 order         : 88217 for Priya

In [39]:
from pydantic import ConfigDict

# model_config tightens the model's behavior.
class StrictPayload(BaseModel):
    model_config = ConfigDict(
        str_strip_whitespace=True,    # trims str fields automatically
        extra="forbid",               # REJECT unknown keys — anti-injection
        frozen=True,                  # instances are immutable (hashable, safe)
        strict=False,                 # keep lax coercion for now
    )
    query: str
    top_k: int = 5

p = StrictPayload(query="   hello   ", top_k="5")
print(p.query, p.top_k)                 # 'hello' — stripped

# Unknown field? Blocked.
try:
    StrictPayload(query="x", override_safety=True)
except ValidationError as e:
    print("Blocked injection attempt:", e.errors()[0]["type"])

hello 5
Blocked injection attempt: extra_forbidden

In [37]:
type(p.top_k)

int